# Inherit style from another configuration
inherit_from: .rubocop_todo.yml

# Apply rule to all cops
AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/schema.rb'
    - 'vendor/bundle/**/*'
    - 'bundle/**/*'
    - 'config/**/*'
    - 'bin/*'

#################### Metrics ###############################

Metrics/LineLength:
  Max: 120